global:
  openshift: true

injector:
  image:
    repository: "docker.io/hashicorp/vault-k8s"
    tag: "1.4.1"

server:
  image:
    repository: "docker.io/hashicorp/vault"
    tag: "1.17.2"
  # OpenShift-specific configurations
  route:
    enabled: true
#    host: "vault-vault.apps.mays-demo.sandbox4175.opentlc.com"
    tls:
      termination: edge

  # Data storage
  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: null

  # Audit storage
  auditStorage:
    enabled: true
    size: 10Gi
    storageClass: null

  # High Availability mode
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true

  # Service configuration
  service:
    enabled: true

  # Standalone mode disabled when HA is enabled
  standalone:
    enabled: false

ui:
  enabled: true
  serviceType: ClusterIP
