---
# Sync OAuth client secret from Vault (for OpenShift OAuth)
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: openshift-oauth-client-secret
  namespace: openshift-config
spec:
  vaultAuthRef: vault/vault-auth
  mount: secret
  type: kv-v2
  path: openshift-config/openshift-oauth-client-secret
  refreshAfter: 30s

  destination:
    name: openshift-oauth-client-secret
    create: true
