apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-vault-role
rules:
  - apiGroups: ["secrets.hashicorp.com"]
    resources: ["vaultauths", "vaultconnections"]
    verbs: ["*"]
