apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instances: 1
  db:
    vendor: postgres
    host: cluster-pg-keycloak-rw.keycloak.svc
    database: keycloak
    usernameSecret:
      name: cluster-pg-keycloak-app
      key: username
    passwordSecret:
      name: cluster-pg-keycloak-app
      key: password
  http:
    tlsSecret: keycloak-certs-letsencrypt
  hostname:
    hostname: test.keycloak.org
  ingress:
    className: openshift-default
