apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-gitlab-role
rules:
  - apiGroups: ["objectbucket.io"]
    resources: ["objectbucketclaims"]
    verbs: ["*"]
  - apiGroups: ["apps.gitlab.com"]
    resources: ["gitlabs"]
    verbs: ["*"]
  - apiGroups: ["postgresql.cnpg.io"]
    resources: ["clusters"]
    verbs: ["*"]
  - apiGroups: ["redis.redis.opstreelabs.in"]
    resources: ["redis"]
    verbs: ["*"]
