apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-operator
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ot-operators

  project: default
  sources:
    - repoURL: https://ot-container-kit.github.io/helm-charts
      chart: redis-operator
      targetRevision: 0.25.0
      helm:
        releaseName: redis-operator
        valueFiles:
          - $values/gitops/ArgoCD-Applications/helm-charts/redis-values/redis-values.yaml
    - repoURL: https://github.com/cmays20/OpenShift-GitLab-Operator-GitOps.git
      targetRevision: HEAD
      path: gitops/ArgoCD-Applications/helm-charts/redis-values
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true