apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ot-operators

  project: default
  sources:
    - repoURL: https://ot-container-kit.github.io/helm-charts
      chart: redis-operator
      targetRevision: 0.25.0
      helm:
        releaseName: redis-operator
        valueFiles:
          - $values/gitops/ArgoCD-Applications/helm-charts/redis-values/redis-values.yaml
    - repoURL: 'GITREPO'
      targetRevision: REVISION
      path: gitops/ArgoCD-Applications/helm-charts/redis-values
      ref: values
    - repoURL: 'GITREPO'
      targetRevision: REVISION
      path: gitops/ArgoCD-Applications/helm-charts/redis-operator-fixes
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: redis-operator
      jsonPointers:
        - /metadata/labels/rbac.authorization.k8s.io~1aggregate-to-admin
        - /rules
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true