apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-seed-secrets
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/cmays20/OpenShift-GitLab-Operator-GitOps.git
    targetRevision: main
    path: gitops/ArgoCD-Applications/helm-charts/vault-seed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
