resources:
  - object-bucket-claims.yaml
  - redis.yaml
  - redis-scc.yaml
  - postgres-cluster.yaml
  - create-object-storage-secrets-job.yaml
  - vault-gitlab-secrets.yaml
  - create-omniauth-secret-job.yaml
  - gitlab-realm-import.yaml
  - gitlab.yaml