apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-cnpg-cluster-role
  namespace: keycloak
rules:
  - apiGroups: ["postgresql.cnpg.io"]
    resources: ["clusters"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

