apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitlab-runner-system

resources:
  - rbac.yaml
  - ca-cert-configmap.yaml
  - create-runner-token-job.yaml
  - vault-runner-token.yaml
  - runner-config.yaml
  - runner.yaml
