apiVersion: apps.gitlab.com/v1beta2
kind: Runner
metadata:
  name: gitlab-runner
  namespace: gitlab-runner-system
  annotations:
    argocd.argoproj.io/sync-wave: "7"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  gitlabUrl: https://gitlab.apps.mays-demo.sandbox3446.opentlc.com
  token: gitlab-runner-registration-token  # Synced from Vault via VSO
  tags: kubernetes, openshift, demo
  buildImage: registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-ocp:latest
  config: gitlab-runner-config  # Reference to ConfigMap containing config.toml
