---
# Sync cmays initial password from Vault
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cmays-initial-password
  namespace: keycloak
spec:
  vaultAuthRef: vault/vault-auth
  mount: secret
  type: kv-v2
  path: keycloak/cmays-initial-password
  refreshAfter: 30s

  destination:
    name: cmays-initial-password
    create: true

---
# Sync OAuth client secret from Vault (for Keycloak)
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: openshift-oauth-client-secret-keycloak
  namespace: keycloak
spec:
  vaultAuthRef: vault/vault-auth
  mount: secret
  type: kv-v2
  path: keycloak/openshift-oauth-client-secret
  refreshAfter: 30s

  destination:
    name: openshift-oauth-client-secret
    create: true
    transformation:
      excludes:
        - .*
      includes:
        - client-secret
