resources:
  - argocd-permissions.yaml
  - cert-manager.yaml
  - odf-lite.yaml
  - cloud-native-pg.yaml
  - keycloak.yaml
  - vault-secrets-operator.yaml
  - web-terminal.yaml
  - oauth.yaml
  - vault-init.yaml
  - vault-seed-secrets.yaml