apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  ignoreDifferences:
    - group: user.openshift.io
      kind: Group
      name: cluster-admins
      jsonPointers:
        - /users
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/OAuth-Setup
    repoURL: 'GITREPO'
    targetRevision: REVISION
  syncPolicy:
    automated:
      selfHeal: true