apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-operator
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/HelmCharts/Redis-Operator/aggregate
    repoURL: 'GITREPO'
    targetRevision: REVISION
  syncPolicy:
    automated:
      selfHeal: true