apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/Operators/VaultSecretsOperator/aggregate
    repoURL: 'GITREPO'
    targetRevision: REVISION
  syncPolicy:
    automated:
      selfHeal: true