resources:
  - ../base

patches:
  - target:
      group: console.openshift.io
      version: v1
      kind: ConsoleLink
      name: gitlab
    patch: |-
      - op: replace
        path: /spec/href
        value: 'https://gitlab.apps.mays-demo.sandbox1374.opentlc.com'